apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
  namespace: springweb
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings-cm
  params:
  - name: buildRevision
    description: The revision of the build, i.e. the commit revision of the application repository
  - name: appGitUrl
    description: The application repository
  - name: configGitUrl
    description: The application config (GitOps) repository
  - name: appImage
    description: The application Docker image name
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.appGitUrl)"
        - name: subdirectory
          value: "app-source-repo"
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "$(params.buildRevision)"

    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: CONTEXT_DIR
          value: "app-source-repo"
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
            - install 
      workspaces:
        - name: maven-settings
          workspace: maven-settings-cm
        - name: source
          workspace: shared-workspace
