apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
  namespace: springweb
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings-cm
    - name: docker-repo
    - name: docker-secret
  params:
  - name: buildRevision
    description: The revision of the build, i.e. the commit revision of the application repository
  - name: appGitUrl
    description: The application repository
  - name: configGitUrl
    description: The application config (GitOps) repository
  - name: pathToContext
    description: The path to cotext in the repo
  - name: imageUrl
    description: Dokcer image URL
  - name: imageTag
    description: Docker tag
  - name: CUSTOM_REGISTRY_SERVER
    default: "docker.io"

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.appGitUrl)"
        - name: subdirectory
          value: "$(params.pathToContext)"
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "$(params.buildRevision)"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: CONTEXT_DIR
          value: "$(params.pathToContext)"
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
            - install 
      workspaces:
        - name: maven-settings
          workspace: maven-settings-cm
        - name: source
          workspace: shared-workspace
          
    - name: build-and-push-image
      taskRef:
        name: kaniko-ap
      runAfter:
        - maven-run
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-repo
        - name: dockersecret
          workspace: docker-secret
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
        - name: CUSTOM_REGISTRY_SERVER
          value: $(params.CUSTOM_REGISTRY_SERVER)
