apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-01
  namespace: springweb
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task can be used to run a Maven build.
    - name: current-date-unix-timestamp
      description: The current date in unix timestamp format
    - name: current-date-human-readable
      description: The current date in human readable format
  workspaces:
    - name: maven-repo
      description: The workspace consisting of maven project.
    - name: shared
      description: Shared workspace
  params:
  - default: Unknown Author
    description: Some input author
    name: author
    type: string
  - default: Unknown 
    description: Some input name
    name: name
    type: string 
  steps:
    - name: mvn-test-repo
      image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
      script: |
        #!/usr/bin/env bash
        echo `date ` - Task: $(params.name) - $(params.author) >> $(workspaces.maven-repo.path)/app.log
 
        ls -all $(workspaces.maven-repo.path)/app.log
        cat $(workspaces.maven-repo.path)/app.log
        ls -all $(workspaces.shared.path)
    - name: print-date-unix-timestamp
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date +%s | tee $(results.current-date-unix-timestamp.path)
    - name: print-date-human-readable
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        date | tee $(results.current-date-human-readable.path) 
