apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
  namespace: springweb
spec:
  workspaces:
    - name: maven-repo
    - name: maven-settings
    - name: shared-workspace
  params:
  - name: buildRevision
    description: The revision of the build, i.e. the commit revision of the application repository
  - name: appGitUrl
    description: The application repository
  - name: configGitUrl
    description: The application config (GitOps) repository
  - name: appImage
    description: The application Docker image name
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.appGitUrl)"
        - name: subdirectory
          value: "app-source"
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "$(params.buildRevision)"
    - name: maven-run-01
      runAfter:
        - fetch-repository
      taskRef:
        name: task-01
      params:
        - name: author
          value: "James"
        - name: name
          value: "1"
      workspaces:
        - name: maven-repo
          workspace: maven-repo
        - name: shared
          workspace: shared-workspace
    - name: maven-run-02
      taskRef:
        name: task-01
      runAfter:
        - maven-run-01
      params:
        - name: author
          value: "Batman"
        - name: name
          value: "2"
      workspaces:
        - name: maven-repo
          workspace: maven-repo
        - name: shared
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
          
